### ISSUE TITLE
1.0.0-rc.5 refuses to start in dark mode inside of Storybook

### ISSUE THREAD

**Issue by hems** [chakra-ui/chakra-ui#2270]
# Bug report

Chakra-ui 1.0.0-rc.5 seems to be ignoring:

 -  `theme.config.initialColorMode` set to `dark`
 - `<ChakraProvider>`'s `initialColorMode` property set to `dark`

Even tough i set `initialColorMode` to dark on my theme or ChakraProvider `mode` to `dark` on my theme Chakra seems to be overwriting the `colorMode` with an empty string.

The [theme used in this example](https://github.com/chakra-ui/chakra-ui/tree/develop/packages/theme/src) was downloaded from chakra-ui repository.

## To reproduce

I have created a repository with only storybook and chakra-ui 1.0.0-rc.5

```bash
git clone https://github.com/hems/chakra-storybook-problem
cd chakra-storybook-problem
y install
y storybook
```

Once storybook is open, check the console and you will see the following console logs:

![image](https://user-images.githubusercontent.com/27327/96523220-118b2900-126d-11eb-90f9-c00eb73eb286.png)

First one is provided by the `ChakraProvider` decorator on Storybook, you can see it [on this file on line 16](https://github.com/hems/chakra-storybook-problem/blob/master/.storybook/preview.js#L16)

````typescript
export const Chakra = ({ children }) => {
  console.log("theme.config ->", newTheme.config)
  
  return (
    <ChakraProvider CSSReset theme={newTheme} initialColorMode="dark">
      <Box p={5}>
        {children}
      </Box>
    </ChakraProvider>
  )
}
````

The two other logs are `useColorMode` hook crated [on this component](https://github.com/hems/chakra-storybook-problem/blob/master/src/stories/0-Welcome.stories.js#L9)

````typescript
const Welcome = ({showApp}) => {
  const { colorMode } = useColorMode();

  console.log('got colormode ->', colorMode)

  return (
    <>
      <Box>
        This is a custom welcome message using Chakra UI
      </Box>
      <Link onClick={showApp} color="teal.500">
        Let's go to see the button
      </Link>
    </>
  )
}
````

## Expected behavior

Chakra component to be rendered using `dark` theme, no the light theme

## Screenshots

![image](https://user-images.githubusercontent.com/27327/96523659-2b793b80-126e-11eb-8344-f94b809b3e5f.png)

## Additional context

 - I have noted in a previous RC version that there was a `localStorage` value called `ui-color-theme` or similar and a second render was happening with such value, but on this RC-5 version i can't find that variable and i'm not sure if that's somehow related.

 - wrapping the component with `<DarkMode>` doesn't seem to work as well.

 - Navigating to another button on the storybook and then coming back to the original story will show two renders, one with `dark` mode and another with `light` mode right after, which i believe demonstrates Chakra is override the `colorMode` at some point?

![image](https://user-images.githubusercontent.com/27327/96525277-72693000-1272-11eb-8292-2e058ff3e523.png)

**Comment by ljosberinn** [comment]
`<ChakraProvider CSSReset theme={newTheme} initialColorMode="dark">` is mixing multiple components props together which can't work.
- `CSSReset` is not a prop, `resetCSS` is, which you do not have to pass explicitly because it's true by default.
- `initialColorMode` is not a prop of `ChakraProvider`, but `ColorModeProvider` which is rendered by `ChakraProvider`
- to forward the `initialColorMode` onto the theme, you need to use:
```js
import { extendTheme } from '@chakra-ui/core';

const customTheme = extendTheme({
  config: {
    initialColorMode: 'dark'
  }
});

<ChakraProvider theme={customTheme}>...</ChakraProvider>
```
See [docs](https://next.chakra-ui.com/docs/migration#2-update-the-themeprovider) and [implementation](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/core/src/chakra-provider.tsx#L13) for reference.

Besides that, there was #2106 which is fixed, but still unreleased.

**Comment by hems** [comment]
> `<ChakraProvider CSSReset theme={newTheme} initialColorMode="dark">` is mixing multiple components props together which can't work.
> 
> * `CSSReset` is not a prop, `resetCSS` is, which you do not have to pass explicitly because it's true by default.
> * `initialColorMode` is not a prop of `ChakraProvider`, but `ColorModeProvider` which is rendered by `ChakraProvider`
> * to forward the `initialColorMode` onto the theme, you need to use:
> 
> ```js
> import { extendTheme } from '@chakra-ui/core';
> 
> const customTheme = extendTheme({
>   config: {
>     initialColorMode: 'dark'
>   }
> });
> 
> <ChakraProvider theme={customTheme}>...</ChakraProvider>
> ```

Apologies about this mess, that was me desperately trying to make it work.

I have previously used exactly the code you provided and it does not work

````
const customTheme = extendTheme({
  config: {
    initialColorMode: 'dark'
  }
});


export const Chakra = ({ children }) => {
  return (
    <ChakraProvider theme={customTheme}>
      <Box p={5}>
        {children}
      </Box>
    </ChakraProvider>
  )
}
````

You can download this repo with `1.0.0-rc.5` and reproduce it yourself.

Here is the [preview.js](https://github.com/hems/chakra-storybook-problem/blob/master/.storybook/preview.js) implemented exactly as your suggestion, and still no luck.

> See [docs](https://next.chakra-ui.com/docs/migration#2-update-the-themeprovider) and [implementation](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/core/src/chakra-provider.tsx#L13) for reference.
> 
> Besides that, there was #2106 which is fixed, but still unreleased.
> 
> The localStorage key [is still there](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/color-mode/src/storage-manager.ts#L4) and you could take inspiration in [how storybook is setup within Chakra itself](https://github.com/chakra-ui/chakra-ui/blob/develop/.storybook/preview.tsx).

Thank you for pointing me out to that, i'll have a look and see if i can make it work based on this.

**Comment by hems** [comment]
Turns out what solved my issue was adding the `preview-head.html` copied from the Chakra storybook.

( :

And apologies about the extra props on the ChakraProvider, that was me naively trying some props that showed up on my auto complete.

**Comment by ljosberinn** [comment]
No worries, glad it worked out :) personally wasn't aware of that file either. Good to know!

**Comment by hems** [comment]
> No worries, glad it worked out :) personally wasn't aware of that file either. Good to know!

It seems that file is the one responsible for setting the default color mode on Storybook!

Without that file the localStorage was empty and it was always starting in light mode regardless of the `initialColorMode` of the theme!
