### ISSUE TITLE
Chakra UI Dark Mode White Screen Flash

### ISSUE THREAD

**Issue by samchungy** [chakra-ui/chakra-ui#2430]
When I run the nextjs-typescript example when you click on different pages on Dark Mode the screen will flash with a white before loading the page. It's not as bad as typing in the URL manually but it's still quite jarring. Any ideas how I can fix this?

Thanks!

Steps to reproduce:

Clone nextjs-typescript
- `npm i framer-motion`
- `npm run dev`
- Click on `View Properties`

**Comment by Prottoy2938** [comment]
I'm facing the same issue. 

I think `chakra-ui` gets its theme preference from the `localStorage`.  So when the page loads, it's initial theme is `light`, but then it checks for theme preference in the `localStorage`, and while it's doing that, we're seeing the `light` mode version of the app.

That's might be the issue.

**Comment by samchungy** [comment]
I think I've fixed it, if you import Chakra in _app.tsx it seems to fix it.

`import {Chakra} from '../Chakra';`

and then wrap the component in it:

`<Chakra><Component {...pageProps} /></Chakra>`

**Comment by Prottoy2938** [comment]
What's in that `Chakra` file?

**Comment by samchungy** [comment]
It contains the ChakraProvider

**Comment by Prottoy2938** [comment]
I'm too using the `ChakraProvider` in the `_app.js` file, but the issue still remains. 

I'm using it like this:

```jsx
import React from "react";
import "../global.styles.css";
import { ChakraProvider } from "@chakra-ui/core";
import customTheme from "../config/chakra-ui/theme";
import { AppProps } from "next/app";
import Head from "next/head";

// This default export is required in a new `pages/_app.js` file.
export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width"
        />
      </Head>
      <ChakraProvider theme={customTheme}>
          <Component {...pageProps} />
      </ChakraProvider>
    </>
  );
}
```



<details><summary>theme.tsx</summary>


<p>

```jsx
import { theme } from "@chakra-ui/core";
import { mode } from "@chakra-ui/theme-tools";
const customTheme = {
  ...theme,
  styles: {
    global: (props) => ({
      body: {
        bg: mode("white", "black")(props),
        color: mode("black", "#E2E8F0")(props),
      },
    }),
  },
  colors: {
    ...theme.colors,
    primary: {
      100: "#CFD1FD",
      200: "#A7ABFB",
      300: "#8388F9",
      400: "#6268F8",
      500: "#444BF7",
      600: "#262EF6",
      700: "#0B14F5",
      800: "#0911DD",
      900: "#080FC7",
    },

    grey: {
      50: "#f0f0fa",
      100: "#d1d3e1",
      200: "#b3b6c9",
      300: "#9499b4",
      400: "#777c9f",
      500: "#5d6385",
      600: "#484d69",
      700: "#34374b",
      800: "#1e212e",
      900: "#080b14",
    },

    cyan: {
      50: "#dbf4ff",
      100: "#addbff",
      200: "#7cc2ff",
      300: "#4aa9ff",
      400: "#1a91ff",
      500: "#0077e6",
      600: "#005db4",
      700: "#004282",
      800: "#002851",
      900: "#000e21",
    },
  },
  fontSizes: {
    xs: "0.75rem",
    sm: "0.875rem",
    md: "1rem",
    lg: "1.1rem",
    xl: "1.25rem",
    "2xl": "1.5rem",
    "3xl": "1.875rem",
    "4xl": "2.25rem",
    "5xl": "3rem",
    "6xl": "4rem",
  },
};

export default customTheme;

```

</p>
</details>

**Comment by ljosberinn** [comment]
It's unavoidable at this point in time. Next renders on the server where we have no knowledge of `localStorage` or `cookies`, so it will always default to the `initialColorMode` defined in `theme.config`. Only after hydration when a user visits the site, it's possible to adapt.

**Comment by davidnussio** [comment]
I have the same problem and I am going to try to follow the information shared [here](https://github.com/vercel/next.js/discussions/12533) but if you have already investigated then I stop and do not waste time. Thank you

**Comment by DecliningLotus** [comment]
@davidnussio, did you develop a working solution with Chakra UI?

**Comment by xencodes** [comment]
any solution?

**Comment by exsesx** [comment]
I solved this problem by using a blocking script right at the top of the body tag in my Next.js project. [Next.js lint doesn't encourage you to do that, by the way](https://nextjs.org/docs/messages/no-sync-scripts).

Another possibly helpful experimental tool, for now, is [Next.js Script Component](https://nextjs.org/docs/basic-features/script). Unfortunately, I didn't find it useful because the `beforeInteractive` strategy is not functional yet.

You can find an example of that script [here](https://github.com/donavon/use-dark-mode/blob/develop/noflash.js.txt).

> Note: you could also use `terser` to minify and then inline that script to improve performance.

**Comment by tombohub** [comment]
is this still issue? In Remix I don't notice flash of light mode

**Comment by NxRoot** [comment]
### For React Users (no SSR)
Add this script below the body of **index.html**
```js
<script>
    function useColor(light="white", dark="#171923"){
      if(typeof window !== "undefined"){
        return window.localStorage.getItem("chakra-ui-color-mode") === "dark" ? dark : light
      } return "white"
    }
    document.body.style.background = useColor();
</script>
```

You might want to specify the correct color for each mode.

**Comment by franchu7** [comment]
I use a button on the pages to change the color mode

**Comment by tuanpq1998** [comment]
After many attempts at researching this problem, no method worked since I was using CSR and there was no way to detect whether the user chose dark or light mode (?). 
I realized that if I didn't use the component having ```useColorModeValue(arg_1, arg_2)``` in the first viewport of the screen load, I didn't encounter this problem when reloading the page because the first component without any bg css will take the default css settings. So I solved it by:
```ts
//NoFlash.tsx
export default function NoFlash({ hide, ...otherProps}: {hide?: booleanotherProps?: AppProps}) {
  console.log({ hide })
  return (
    <Box display={hide ? 'none' : undefined}
      //visibility={hide ? 'hidden' : 'visible'}
      //opacity={hide ? 0 : 1}
      w={'100vw'}
      h={hide ? 0 : '100vh'}/>
  )
}
``` 
```ts
//_app.tsx

export default function App({ Component, pageProps }: AppProps) {
  const mainRef = useRef<HTMLDivElement>(null)
  const [hideNoFlash, { on: setHideNoFlashTrue }] = useBoolean(false)

  useEffect(() => {
    setHideNoFlashTrue()
  })

  return (
    <>
      <ChakraProvider theme={theme}>
        <NoFlash hide={hideNoFlash} />
        <Component forwardRef={mainRef} {...pageProps} />
      </ChakraProvider>
    </>
  )
}

```
I'm not sure if this affects SEO, since it shows a no-content screen on the loading screen. You could add a transition to make it smoother, or maybe a skeleton to avoid the no-content screen altogether.

**Comment by louisnt** [comment]
This fixed this issue for me 🎉

Add ColorModeScript to _document:


`
import { ColorModeScript } from "@chakra-ui/react";
import theme from "@/styles/theme";

...
  <Box as="body" suppressHydrationWarning>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Main />
        <NextScript />
      </Box>
      ...
`

**Comment by itamarzil12345** [comment]
I had also experienced the same symptoms. However none of the above solutions worked for me. What solved for me is just take theme directly from the localStorage and use it. Inside any component that uses the theme:
const theme = localStorage.getItem('chakra-theme-key...')
which makes sure only the correct theme is loaded. Any thoughts feedback on this solution ?

**Comment by walsh-rose-ai** [comment]
Here is our `pages/_document.tsx`:

```ts
import { chakraThemeConfig } from '@/theme';
import { ColorModeScript } from '@chakra-ui/react';
import { Head, Html, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body className="bg-rose-primary-bg">
        {/* "For Next.js, you need to add the ColorModeScript to the _document.js file." See https://v2.chakra-ui.com/docs/styled-system/color-mode#for-nextjs. */}
        <ColorModeScript initialColorMode={chakraThemeConfig.initialColorMode} />
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}

```

The flicker / flash is definitely a problem for us.

https://v2.chakra-ui.com/docs/styled-system/color-mode#color-mode-flash-issue says:

> ## Color Mode Flash Issue
> In some cases, when you switch to dark mode and refresh the page, you might experience a quick flash of light mode before it switches correctly.
> 
> This is a known issue and we're looking to fix it.

But this issue is closed. 

Is there an open issue I can track?

**Comment by ryancwalsh** [comment]
Here is our `pages/_document.tsx`:

```ts
import { chakraThemeConfig } from '@/theme';
import { ColorModeScript } from '@chakra-ui/react';
import { Head, Html, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html lang="en">
      <Head />
      <body className="bg-rose-primary-bg">
        {/* "For Next.js, you need to add the ColorModeScript to the _document.js file." See https://v2.chakra-ui.com/docs/styled-system/color-mode#for-nextjs. */}
        <ColorModeScript initialColorMode={chakraThemeConfig.initialColorMode} />
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}

```

The flicker / flash is definitely a problem for us.

https://v2.chakra-ui.com/docs/styled-system/color-mode#color-mode-flash-issue says:

> ## Color Mode Flash Issue
> In some cases, when you switch to dark mode and refresh the page, you might experience a quick flash of light mode before it switches correctly.
> 
> This is a known issue and we're looking to fix it.

But this issue is closed. 

Is there an open issue I can track?

**Comment by xamgore** [comment]
Prefer the theme loader from the [`next-themes`](https://github.com/pacocoursey/next-themes), it was specifically made to prevent white flickering. The fresh templates with Chakra UI already use it.
