### ISSUE TITLE
Menu popper gets cut off when component is far right

### ISSUE THREAD

**Issue by t0ngliu** [chakra-ui/chakra-ui#31]
I created a sandbox with the defect https://codesandbox.io/s/chakra-ui-sandbox-9e5v4
Note that the menu popper gets cut off when component is far right.

Loving the library! 😃

**Comment by Vynlar** [comment]
Just spent some time playing around with this and have uncovered some helpful info. If you scroll the view while the menu is open `react-popper`, the internal library responsible for the menu's position, fixes the problem demonstrated. This means that if we can figure out a way to get `react-popper` to perform this correct positioning from the beginning the bug should be resolved.

See: https://codesandbox.io/s/chakra-ui-sandbox-q64tc

- Open one of the menus
- Notice it goes off the screen
- Scroll the page a little bit
- Notice the menu moves into place

**Comment by segunadebayo** [comment]
I agree @Vynlar. We'll need to find a way to get `react-popper` to handle this scenario. 

I'll look into this as well and resolve it from storybook first, then I'll release a patch.

**Comment by segunadebayo** [comment]
@t0ngliu. I've resolved this issue and will release a patch soon.

@Vynlar I had to replace the `react-popper` library with `popper.js` to gain more control over the behavior of the popper.

**Comment by valstu** [comment]
I think this issue still exists 🤔 You can use the same example that was linked above and update the dependencies to latest and it's still making this weird jumping movement.

**Comment by jana-uoft** [comment]
I had the same issue and resolved it by adding style `right={0}` to the `MenuList` component. 
```
      <MenuList
        right={0}
        width={150}
        bg={bgColor[colorMode]}
        color={color[colorMode]}
      >
        {menuItems.map(renderMenuItem)}
      </MenuList>
```

I also set a fixed width to have consistent behaviour on mobile as well. 

Hope this helps 😃
