### ISSUE TITLE
[ListIcon] TypeError: Cannot read property 'question-outline' of undefined

### ISSUE THREAD

**Issue by BadMask121** [chakra-ui/chakra-ui#430]
**Describe the bug**
ListIcon not working with nextjs ^9.2.1

**Expected Behavior**

**To Reproduce**
- Use this template:
- List the steps to reproduce the behavior:

**Suggested solution(s)**

**Desktop (please complete the following information):**

**Additional context**

**Comment by segunadebayo** [comment]
Hi @BadMask121.

This isn't a proper issue description, kindly update it please.

However, this seems like you're not wrapping your entire application with ThemeProvider from Chakra UI.

**Comment by nicco88** [comment]
I had this same error, even by wrapping the whole app with ThemeProvider. I wanted to use chakra UI's default icons, but later realized I hadn't included `theme.icons` inside my customTheme's `icons` property, so it couldn't find those, hence the error... a better error message would have helped, but anyway, this should solve the problem in case anybody else gets this error.

**Comment by MikePreston17** [comment]
PSA: This also happens when you forget to define an svg icon in your customTheme (theme.js) but instance it in a React component:

__theme.js:__
```
// Add Chakra's icons
    ...theme.icons,
    // Your custom icons
    search: {
        // The <path/> or <g> element for the svg. Note the use of  `fill=currentColor`
        path: (
            <path
                fill="currentColor"
                d="..."
            />
        ),
        // This is the viewBox of the icon.
        viewBox: "0 0 24 24",
    },
    // NOTE: The 'missing' svg
    // typescript: {
    //     path: <path fill="currentColor" d="..."></path>,
    //     viewBox: "0 0 40 40",
    // }
```
__Skills.js:__

```
export const Skills = () => {
    return (
        <Stack alignItems='left'>
            <Heading>My Skills</Heading>
            <Icon name='typescript' ></Icon> {* Right here, the typescript icon is instanced *}

            <Box 
                alignContent='left'
                justifyContent='left'
            >
                <i>{disclaimer}</i>
            </Box>
        </Stack>
    )
}
```

**Comment by MikePreston17** [comment]
Regarding my post above, I'm still having issues, so it may not actually have anything to do with Icons at all.  Working on it.

**Comment by austinlxx** [comment]
My solution was to put `ThemeProvider` at the highest level, which in my NextJS app was in `_app.js`

```
    <ThemeProvider>
      <Component {...pageProps} />
    </ThemeProvider>
```
