### ISSUE TITLE
[Image] onError is not called

### ISSUE THREAD

**Issue by laurensnl** [chakra-ui/chakra-ui#507]
**Describe the bug**
The `onError` callback is not called when the `src` cannot be loaded. See the code sandbox for an example. The `fallbackSrc` is successfully loaded, but in the attached example not being shown because the `onError` callback is not called.

**Expected Behavior**
I would expect the `onError` callback to be called when the `src` image cannot be loaded.

**To Reproduce**
https://codesandbox.io/s/serverless-monad-wuijx

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.3
 - Browser Chrome, Safari
 - Version 80

**Additional context**

**Comment by blnk-space** [comment]
Hi! Faced the same issue and I have fixed it, creating a PR shortly.

**Comment by blnk-space** [comment]
Just created a PR for this #510, @segunadebayo please review and merge if you deem it fit!

**Comment by segunadebayo** [comment]
Thank you @blnk-space. It's merged!

I will release a patch by tomorrow.

**Comment by laurensnl** [comment]
Thank you for fixing this @blnk-space & @segunadebayo! When will it be released?

**Comment by asimplify** [comment]
issue still not resolved not detecting broken images in onError callback
