### ISSUE TITLE
"chakra-cli tokens" command fails

### ISSUE THREAD

**Issue by kculmback** [chakra-ui/chakra-ui#5219]
### Description

Trying to run the `chakra-cli tokens` command fails with error: `TypeError: Cannot read properties of undefined (reading 'message')`.

### Link to Reproduction

https://github.com/kculmback/chakra-bug

### Steps to reproduce

1. Download reproduction repo
2. Run `npm install`
3. Run `npm run gen:theme-typings`
4. See error:
```
TypeError: Cannot read properties of undefined (reading 'message')
    at yx (node_modules/prettier/parser-typescript.js:13:3304348)
    at Object.parse (node_modules/prettier/parser-typescript.js:13:3304817)
    at Object.parse$d [as parse] (node_modules/prettier/index.js:12975:19)
    at coreFormat (node_modules/prettier/index.js:14525:16)
    at formatWithCursor$1 (node_modules/prettier/index.js:14765:14)
    at node_modules/prettier/index.js:60959:14
    at Object.format (node_modules/prettier/index.js:60979:12)
    at node_modules/@chakra-ui/cli/src/utils/format-with-prettier.ts:8:19
    at async run (node_modules/@chakra-ui/cli/src/scripts/read-theme-file.worker.ts:113:20)
```

### Chakra UI Version

1.7.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Chakra v1.7.3
Chakra CLI v1.6.0
Node v16.13.1

Repo was made using Vite; used `npm init vite@latest` and selected `react-ts`. Added Chakra and Chakra CLI, theme file, and command to generate theme typings.

**Comment by sinnrrr** [comment]
Same here, m1 mac

**Comment by jrolfs** [comment]
I don't think #5225 fixes this for me. I already had Prettier installed when I was having this issue and `require('prettier')` resolved just fine from within **@chakra-ui/cli**. I pulled down @kculmback's repository and sure enough, it also has **prettier@2.5.1** installed and I was able to reproduce the issue.

Just to be sure, I installed the **@chakra-ui/cli** release from #5225, and I was still able to reproduce the issue ↯

<img width="973" alt="cli-hang-💥" src="https://user-images.githubusercontent.com/288160/146463106-07671fdc-a0c2-462c-93a5-5167ecaa43b4.png">

The process also seems to hang for quite some time before failing with the error. The callstack from the error is also deep within Prettier, so I think this may actually be a bug with Prettier.

Interestingly I'm also on an M1 MacBook Air, @segunadebayo + @TimKolberger are you able to reproduce the error at all in @kculmback's repo? I also forked it and installed the CLI from @TimKolberger's branch → https://github.com/jrolfs/chakra-bug

I'm going to keep digging into this as it's currently holding me back from upgrading Chakra in our component library because the new versions of Chakra require the CLI with the updated output path.

**Comment by jrolfs** [comment]
@kculmback are you on an M1 by any chance?

**Comment by jrolfs** [comment]
Alight, I had a coworker reproduce it on `x86_64` so I don't think it's ARM-related ... that would have been super weird anyways.

**Comment by jrolfs** [comment]
I'm able to reproduce it on Codesandbox too: https://codesandbox.io/s/chakra-cli--t0ho5 (hangs for even longer though, fyi)

**Comment by kculmback** [comment]
If I point my project to the latest update for `@chakra-ui/cli` it still does not work for me. I am not on an M1 mac. I also have `prettier` installed as a dev dependency in other projects where this issue is happening (even though it is not installed in the reproduction repo I linked above). 

The error I get is still the same as before:
```
✖ An error occurred
TypeError: Cannot read properties of undefined (reading 'message')
    at yx (/Users/kasey/www/kc/chakra-bug/node_modules/prettier/parser-typescript.js:13:3304348)
    at Object.parse (/Users/kasey/www/kc/chakra-bug/node_modules/prettier/parser-typescript.js:13:3304817)
    at Object.parse$d [as parse] (/Users/kasey/www/kc/chakra-bug/node_modules/prettier/index.js:12975:19)
    at coreFormat (/Users/kasey/www/kc/chakra-bug/node_modules/prettier/index.js:14525:16)
    at formatWithCursor$1 (/Users/kasey/www/kc/chakra-bug/node_modules/prettier/index.js:14765:14)
    at /Users/kasey/www/kc/chakra-bug/node_modules/prettier/index.js:60959:14
    at Object.format (/Users/kasey/www/kc/chakra-bug/node_modules/prettier/index.js:60979:12)
    at _callee$ (/Users/kasey/www/kc/chakra-bug/node_modules/@chakra-ui/cli/src/utils/format-with-prettier.ts:8:19)
    at tryCatch (/Users/kasey/www/kc/chakra-bug/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/kasey/www/kc/chakra-bug/node_modules/regenerator-runtime/runtime.js:294:22)
```

@TimKolberger @segunadebayo

**Comment by jrolfs** [comment]
@kculmback how were you pointing it at your local `chakra-ui` install? Were you using `npm link`?

**Comment by ahrbil** [comment]
I'm using the latest version of chakra-cli on Windows and I have prettier installed as well,
but I'm still getting the error.

**Comment by kculmback** [comment]
> @kculmback how were you pointing it at your local `chakra-ui` install? Were you using `npm link`?

Yup

**Comment by sinnrrr** [comment]
Still have issues with this, tried installing prettier as dev dependency, but that didn’t work either as @kculmback

**Comment by ducpt2** [comment]
I had the same issue, looking for a new version to fix this. Thanks.

**Comment by TimKolberger** [comment]
I pushed a fix for this which works on my machine (yay) with this project: https://github.com/kculmback/chakra-bug

You can try this version by installing this version of `@chakra-ui/cli` in your `package.json`:

```
"@chakra-ui/cli": "0.0.0-pr-20211126153854",
```

Let me know if there are still issues in your project.

**Comment by kculmback** [comment]
@TimKolberger That PR did indeed fix the issue for me 👍🏻 👍🏻 Thanks!

**Comment by katsenkatorz** [comment]
> 0.0.0-pr-20211126153854

I'have same problem for me on m1, this PR fix this for me to ! Thx @TimKolberger

**Comment by ducpt2** [comment]
Hi @TimKolberger , i still have this issue, please help me. I use below version:
"@chakra-ui/react": "^1.7.3",
"@chakra-ui/cli": "0.0.0-pr-20211126153854",
"react": "^17.0.2",

And use the theme.ts file like flow link:
https://chakra-ui.com/docs/theming/advanced
https://chakra-ui.com/docs/theming/customize-theme

When i run the command chakra-cli tokens --path/theme.ts, it said success for generating chakra ui theme.
But i can't see any file generate, and whene i test chakra component like above link, it not suggest at all.
Did i miss something in here. Thanks

**Comment by TimKolberger** [comment]
The token command updates the theming.types.ts file in your node_modules.

Please check node_modules/@chakra-ui/styled-system/dist/declarations/src/theming.types.d.ts

**Comment by TimKolberger** [comment]
You can provide another out file with:

npx @chakra-ui/cli tokens src/theme.ts --out theme-typings.d.ts

**Comment by ducpt2** [comment]
hi @TimKolberger , wow, so fast response. Thanks.
I use this command npx @chakra-ui/cli tokens src/theme.ts --out theme-typings.d.ts and saw my expected types are generated. In my case is `const theme = extendTheme({
  colors: {
    brand: {
      100: "#f7fafc",
      // ...
      900: "#1a202c",
    },
  },
})`
But when i test it with Box in my App.tsx (had ThemeProvider) it not showing auto suggestion at all.
https://chakra-ui.com/docs/theming/customize-theme
Do you have some clues? Thanks

**Comment by TimKolberger** [comment]
Just omit the out parameter and it should work. By updating the file in the node_modules (default behavior) it is automatically used for autocomplete.

**Comment by ducpt2** [comment]
Wow, @TimKolberger it work now, i just restart my vscode and it start to work now. Awesome.
Just one more question, i see we are using PR and not merge to main branch yet. If i want to use main branch, i just need to wait a little bit, right? Thanks

**Comment by TimKolberger** [comment]
That's great to hear!

It is merged to main and will need to wait for next release. 
I think it'll be early next year... 😅

**Comment by ducpt2** [comment]
Great to hear that. Thanks.

**Comment by Crizzooo** [comment]
Im in a yarn monorepo.

When I run the command, I see it updates `theming.types.d.ts` inside of the **dist** folder of `styled-system`. 

But when I inspect the current definition in VSCode, it seems to be reading the EmptyThemeTypings inside of the src.

Any color here on which one is expected to be updated, and which one is expected to be read when running the command?

**Comment by morellodev** [comment]
Any update on this? I am on an Intel MacBook Pro with the following packages:

- `@chakra-ui/react@1.8.6`
- `@chakra-ui/cli@1.9.0`

and I have the same issue as https://github.com/chakra-ui/chakra-ui/issues/5219#issuecomment-996476852

**Comment by mattcoker** [comment]
Same as @morellodev, I'm also still having the same issues, confirmed running @chakra-ui/cli 1.9.0. It was working about 1.5 months ago, but now I'm getting that same prettier error.

**Comment by mattcoker** [comment]
It seems that updating my prettier version from `2.5.1` to `2.6.1` has resolved the issue for me

**Comment by mattcoker** [comment]
Somehow, the issue has started back up again. I'll update here as soon as I figure out the cause.

**Comment by morellodev** [comment]
I temporarily solved the problem by adding this to the `package.json` file:

```json
"resolutions": {
  "prettier": "2.5.1"
}
```

**Comment by mattcoker** [comment]
@morellodev This works great as a temporary measure, thanks!

**Comment by lucasfranchini** [comment]
any news on this? i'm using Ubuntu 20.04 with:
 - @chakra-ui/cli@1.9.0
 - @chakra-ui/react@1.8.6
 - prettier 2.6.1
Still have the issue like #5219 and @morellodev solution didn't work for me.

**Comment by OnielN14** [comment]
> ```json
> "resolutions": {
>   "prettier": "2.5.1"
> }
> ```

Maybe you can try to downgrade prettier to 2.5.1.

**Comment by OnielN14** [comment]
> any news on this? i'm using Ubuntu 20.04 with:
> 
> * @chakra-ui/cli@1.9.0
> * @chakra-ui/react@1.8.6
> * prettier 2.6.1
> 
> Still have the issue like #5219 and @morellodev solution didn't work for me.

Maybe you can try to downgrade prettier to 2.5.1.

**Comment by lucasfranchini** [comment]
I downgraded it and it works thank you @OnielN14!

**Comment by jordanrastrick** [comment]
I'm seeing this issue both locally on Mac OS Sonoma and also on Linux in CI/CD. I have:

- "@chakra-ui/cli": "1.9.0"
- "@chakra-ui/react": "1.8.9"
- "prettier": "2.8.8"

If per @OnielN14 's suggestion  I fix `prettier` for `@chakra-ui/cli` to `2.5.1` via a yarn resolution (so as not to mess with the `prettier` version for the rest of the codebase) this fixes the problem. But I don't think it's a great long term solution.
