### ISSUE TITLE
Warning Extra attributes from the server class

### ISSUE THREAD

**Issue by sawa-ko** [chakra-ui/chakra-ui#7040]
### Description

When I use the "ColorModeScript" component in next v13 I get the following error in the browser console.

```tsx
'use client';

import { ReactNode } from 'react';

import theme from '@/lib/chakra-ui/theme';
import { ChakraProvider, cookieStorageManagerSSR, localStorageManager } from '@chakra-ui/react';

type CustomChakraProviderProps = {
    children: ReactNode;
    cookie?: string | null;
};

function CustomChakraProvider({ children, cookie }: CustomChakraProviderProps) {
    return (
        <ChakraProvider resetCSS theme={theme} colorModeManager={cookie ? cookieStorageManagerSSR(cookie) : localStorageManager}>
            {children}
        </ChakraProvider>
    );
}

export { ColorModeScript } from '@chakra-ui/react';
export default CustomChakraProvider;
```

```tsx
// I tried using "use client" here too, but same error.

import CustomChakraProvider, { ColorModeScript } from '@chakra-ui/react';

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html>
            <head />
            <body>
                <ColorModeScript initialColorMode={'system'} type={'localStorage'} />
                <CustomChakraProvider>
                    {children}
                </CustomChakraProvider>
            </body>
        </html>
    );
}
```

### Link to Reproduction

https://stackblitz.com/edit/vercel-next-js-tzxuxl?file=app/page.tsx

### Steps to reproduce

1. Create a nextjs v13 project
2. Try use `ColorModeScript` in the `layout.js` (with or without `"use client;"` on top) file
3. Check browser console

### Chakra UI Version

2.4.1

### Browser

Microsoft Edge 107.0.1418.56

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://user-images.githubusercontent.com/56084970/204071069-a83a3361-1c5d-453d-9595-4d69fc087e62.png)

**Comment by Masaki-G** [comment]
Hello! I'm also facing the same issue here!

**Comment by NazarLysyi** [comment]
I have this problem too (

**Comment by wouter-deen** [comment]
Same issue here. For me it's at a button and the error I get is `Extra attributes from the server: control-id`. I have a feeling that it has to do with some dynamic props. Will investigate further.

**Comment by Inam-ulrehman** [comment]
Same issue only in development not in production like on Vercel there is no error.

**Comment by BEDIRHANSAMSA** [comment]
same

**Comment by jianshangquan** [comment]
same

**Comment by elewin** [comment]
I get a 

```Warning: Extra attributes from the server: control-id```

error as well

**Comment by tolgaand** [comment]
any update?

**Comment by diogomartino** [comment]
I also get a warning:

```
errors.js:38 Warning: Extra attributes from the server: class
    at body
    at html
    at RedirectErrorBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/components/redirect-boundary.js:73:9)
    at RedirectBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/components/redirect-boundary.js:81:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/components/not-found-boundary.js:51:9)
    at NotFoundBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/components/not-found-boundary.js:59:11)
    at ReactDevOverlay (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
    at HotReload (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:276:11)
    at Router (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/components/app-router.js:90:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/components/error-boundary.js:77:9)
    at ErrorBoundary (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/components/error-boundary.js:101:11)
    at AppRouter (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/components/app-router.js:387:13)
    at ServerRoot (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/app-index.js:154:11)
    at RSCComponent
    at Root (webpack-internal:///(app-client)/./node_modules/.pnpm/next@13.4.5_cpvzbyutg2okhbbkipcbqd7uwi/node_modules/next/dist/client/app-index.js:171:11)
```

I'm almost certain that it's coming from this library.

**Comment by TaufiqSyed** [comment]
Yeah this issue is still popping up. Would be great if anyone has an explanation / solution for this.

**Comment by elewin** [comment]
I’m starting to think it might be unrelated chrome plugins causing this, can anyone confirm ?

**Comment by TaufiqSyed** [comment]
@elewin I have tried this on incognito to no avail. Also tried suppressing hydration warnings. The only thing that does the trick is commenting out "<ColorModeScript />" inside the layout.tsx file, which reduces functionality. (As a note, I tried the Chakra UI Next JS GitHub example, and it throws the same error on the console)

**Comment by TTBOBO** [comment]
I've fixed the problem, try rendering the ColorModeScript after the page is mounted!

 const [mounted, setMounted] = useState(false);
 useEffect(() => setMounted(true), []);
 {mounted && <ColorModeScript initialColorMode={theme.config.initialColorMode}></ColorModeScript>}

**Comment by nt9142** [comment]
> Yeah this issue is still popping up. Would be great if anyone has an explanation / solution for this.

The `<ColorModeScript />` [injects](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/color-mode/src/color-mode-script.tsx#L45) a `<script>` that immediately updates `body`'s class attribute by values `chakra-ui-light` or `chakra-ui-dark` using DOM API as soon as the browser reads it. Afterwards, React's hydration process begins. it discovers mismatches between the server-rendered content and the content after hydration.

Why the discrepancy with the "server-rendered" content? Technically, the server returns the initial content without these class changes. However, the injected `<script>` modifies the class attribute, leading React to observe the updated version, which is different from the original server-rendered content.

I have no idea why this does not happen in the [Pages router](https://nextjs.org/docs/pages) in Next.js. I've only observed this behaviour in the [App router](https://nextjs.org/docs/app).

On a side note, technically, you could manually insert a className to the body to circumvent this issue, but it's a rather hacky solution.

**Comment by nt9142** [comment]
> Yeah this issue is still popping up. Would be great if anyone has an explanation / solution for this.

The `<ColorModeScript />` [injects](https://github.com/chakra-ui/chakra-ui/blob/f5b1a3569fd0c654897d2397b3d0bd4677783fa7/packages/components/color-mode/src/color-mode-script.tsx#L45) a `<script>` that immediately updates `body`'s class attribute by values `chakra-ui-light` or `chakra-ui-dark` using DOM API as soon as the browser reads it. Afterwards, React's hydration process begins. React discovers mismatches between the server-rendered content and the content after hydration.

Why the discrepancy with the "server-rendered" content? Technically, the server returns the initial content without these class changes. However, the injected `<script>` modifies the class attribute, leading React to observe the updated version, which is different from the original server-rendered content.

I have no idea why this does not happen in the [Pages router](https://nextjs.org/docs/pages) in Next.js. I've only observed this behaviour in the [App router](https://nextjs.org/docs/app).

On a side note, technically, you could manually insert a className to the body to circumvent this issue, but it's a rather hacky solution.

**Comment by milottit** [comment]
So apparently chakra-ui can fix this "warning".

Maybe when the page request is made to the server, they could send the `colorMode` value (from the system and preferences), and then set the correct `colorMode` according to the `{ initialColorMode, useSystemColorMode }: ThemeConfig`.

**Comment by marqpdx** [comment]
> > Yeah this issue is still popping up. Would be great if anyone has an explanation / solution for this.
>  ...
> On a side note, technically, you could manually insert a className to the body to circumvent this issue or add a `suppressHydrationWarning` prop to `body` and `html`, but it's a rather hacky solution.

@nt9142 - i did try adding a className to body, but that through another warning, and i tried `suppressHydrationWarning` in <body>, literally the line immediately before ColorModeScript and it still throws the warning.

**Comment by SebastianCoceres** [comment]
This can be resolved by placing the ColorModeScript inside the Chakra provider provided by Chakra for Next.js within the "app" directory:

"use client";

import { CacheProvider } from "@chakra-ui/next-js";
import { ChakraProvider, ColorModeScript } from "@chakra-ui/react";
import { theme } from "@/styles/theme";

export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <CacheProvider>
      <ChakraProvider
        theme={theme}
        toastOptions={{
          defaultOptions: { position: "bottom", isClosable: true },
        }}
      >
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        {children}
      </ChakraProvider>
    </CacheProvider>
  );
}

**Comment by CaioMS2000** [comment]
> 

For me doesn't matter where I put the ColorModeScritp tag, it still print some warning, so I had to put "suppressHydrationWarning={true}" flag on "html" and "body" tags in RootLayout, each one supress a different warning.
My libs versions:
```
"@chakra-ui/next-js": "^2.1.5",
"@chakra-ui/react": "^2.8.0",
"@emotion/react": "^11.11.1",
"@emotion/styled": "^11.11.0",
"framer-motion": "^10.15.1",
"next": "13.4.13",
```

**Comment by Donal2** [comment]
in root layout.js

`<html lang="en" suppressHydrationWarning={true}>`

does the job

thank you @CaioMS2000

**Comment by duplxey** [comment]
Setting `supressHydrationWarning={true}` on `html` didn't work for me.

**Comment by sangdth** [comment]
Is it bad to prevent that script on server side?

```
const ColorModeScript = dynamic(
  () => import('@chakra-ui/react').then((mod) => mod.ColorModeScript),
  { ssr: false }
);
```

This way the warning is gone but I don't know the downside of it.

**Comment by aashikdevelop** [comment]
> in root layout.js
> 
> `<html lang="en" suppressHydrationWarning={true}>`
> 
> does the job
> 
> thank you @CaioMS2000

Thank you

**Comment by Y0SH4** [comment]
any update? 
i get same issue

**Comment by davidmonnom** [comment]
```    
<html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
```

A little hack while we wait for `colorModeSript` to be compatible with the app directory.

Please note, however, that this only hides the error - it's still there.

---

Other information, these types of errors:
![image](https://github.com/chakra-ui/chakra-ui/assets/63289800/184a689b-0538-4871-91f3-a555c9a988e7)
Are often due to an extension, here for example, this error appears because I have LanguageTools installed.

**Comment by abhishektyagi2912** [comment]
> Same issue here. For me it's at a button and the error I get is `Extra attributes from the server: control-id`.
> 
> Edit: no matter what button component I add or delete, even a single button in my page still results in this warning. Below is my full warning:
> 
> Full warning

This is usually caused by an extension passing these extra attributes with your code when it is executed on the browser trying to interact with the UI, this creates a mismatch between what was rendered on the server and what is rendered on the client.

Extensions similar to Grammarly, ColorZilla and LanguageTool are therefore the cause of this warning, so you have to find out which one is doing this and then disable/configure it to not run on the ports you usually use for development. This is the straightforward fix for the warining, since it is always recommended to avoid extensions in development.

**Comment by nicovalencia** [comment]
A `é` character (even unicode escaped) causes this for me.

**Comment by KangWoosung** [comment]
```
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={inter.className}
        suppressHydrationWarning={true}
        suppressContentEditableWarning={true}
      >
```
      This worked out for my case.

**Comment by segunadebayo** [comment]
Closing based on https://github.com/chakra-ui/chakra-ui/issues/7040#issuecomment-2339282060

Please enable suppressHydrationWarning on the html element
