### ISSUE TITLE
Named export 'chakra' not found. The requested module '@chakra-ui/system' is a CommonJS module, which may not support all module.exports as named exports.

### ISSUE THREAD

**Issue by zwelhtetyan** [chakra-ui/chakra-ui#7170]
### Description

**### I face this Error when i add ChakraIcon in my nextjs(13.1.1) project.**

![Screenshot from 2022-12-27 11-01-58](https://user-images.githubusercontent.com/89287841/209611532-e73b5a90-6175-43fb-833d-a7dd22013466.png)

### Link to Reproduction

https://github.com/zwelhtetyan/realtor-zhy

### Chakra UI Version

2.4.4

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by SumitNalavade** [comment]
Downgrading @chakra-ui/react to exactly "2.4.2" seems to work for me.

**Comment by AnujSsStw** [comment]
same for me 
![Screenshot from 2022-12-27 18-34-09](https://user-images.githubusercontent.com/92370865/209670771-d24c9e86-dfbe-466e-9ec3-0a37c0295314.png)

**Comment by AnujSsStw** [comment]
> 2.4.2

NO BRO it still the same for me

**Comment by AE-0h** [comment]
the only thing that has worked for me so far is adding :
  experimental: {
    esmExternals: false,
}

to my next.config.js
not a permanent fix but it will get your page to compile and render.

Any other thoughts from ChakraUI peeps?
Hopefully they fix this bug soon.

**Comment by AE-0h** [comment]
> > 2.4.2
> 
> NO BRO it still the same for me

can you take a screenshot of your package.json?

**Comment by shinebayar-g** [comment]
Yup this happened after the update.

```
 @chakra-ui/react     ^2.4.4  →     ^2.4.5
```

Pin to previous version `"@chakra-ui/react": "2.4.4",` like this for now until it's fixed.

**Comment by tiankaixie** [comment]
Same issues here. Both 2.4.2 and 2.4.4 do not work for me. My package.json is:

```{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@chakra-ui/icons": "^2.0.15",
    "@chakra-ui/react": "2.4.2",
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@headlessui/react": "^1.6.4",
    "@heroicons/react": "^1.0.6",
    "axios": "^0.27.2",
    "bootstrap": "^5.2.0",
    "eslint": "^8.29.0",
    "eslint-config-next": "^13.1.1",
    "fast-kde": "^0.2.1",
    "framer-motion": "^8.0.2",
    "next": "^13.1.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "valtio": "^1.6.1"
  },
  "devDependencies": {
    "@types/node": "17.0.4",
    "@types/react": "17.0.38",
    "@typescript-eslint/eslint-plugin": "^5.45.0",
    "autoprefixer": "^10.4.0",
    "eslint-config-standard-with-typescript": "^23.0.0",
    "eslint-plugin-import": "^2.25.2",
    "eslint-plugin-n": "^15.0.0",
    "eslint-plugin-promise": "^6.0.0",
    "eslint-plugin-react": "^7.31.11",
    "postcss": "^8.4.5",
    "prettier": "^2.5.1",
    "typescript": "*"
  }
}
```

**Comment by AE-0h** [comment]
> Same issues here. Both 2.4.2 and 2.4.4 do not work for me. My package.json is:
> 
> ```
>   "private": true,
>   "scripts": {
>     "dev": "next dev",
>     "build": "next build",
>     "start": "next start"
>   },
>   "dependencies": {
>     "@chakra-ui/icons": "^2.0.15",
>     "@chakra-ui/react": "2.4.2",
>     "@emotion/react": "^11.10.5",
>     "@emotion/styled": "^11.10.5",
>     "@headlessui/react": "^1.6.4",
>     "@heroicons/react": "^1.0.6",
>     "axios": "^0.27.2",
>     "bootstrap": "^5.2.0",
>     "eslint": "^8.29.0",
>     "eslint-config-next": "^13.1.1",
>     "fast-kde": "^0.2.1",
>     "framer-motion": "^8.0.2",
>     "next": "^13.1.1",
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
>     "valtio": "^1.6.1"
>   },
>   "devDependencies": {
>     "@types/node": "17.0.4",
>     "@types/react": "17.0.38",
>     "@typescript-eslint/eslint-plugin": "^5.45.0",
>     "autoprefixer": "^10.4.0",
>     "eslint-config-standard-with-typescript": "^23.0.0",
>     "eslint-plugin-import": "^2.25.2",
>     "eslint-plugin-n": "^15.0.0",
>     "eslint-plugin-promise": "^6.0.0",
>     "eslint-plugin-react": "^7.31.11",
>     "postcss": "^8.4.5",
>     "prettier": "^2.5.1",
>     "typescript": "*"
>   }
> }
> ```

change your react/icons to "2.0.13"
you have to used exact versions so remove the caret in front of each version.  For example you have  "@chakra-ui/icons": "^2.0.15" when it should be "@chakra-ui/icons": "2.0.15". same with "@chakra-ui/react": "2.4.2" also make sure you delete current node_modules and package.json-lock and re-install all of your dependencies with npm i.  I hope this helps!!

**Comment by tiankaixie** [comment]
> > Same issues here. Both 2.4.2 and 2.4.4 do not work for me. My package.json is:
> > ```
> >   "private": true,
> >   "scripts": {
> >     "dev": "next dev",
> >     "build": "next build",
> >     "start": "next start"
> >   },
> >   "dependencies": {
> >     "@chakra-ui/icons": "^2.0.15",
> >     "@chakra-ui/react": "2.4.2",
> >     "@emotion/react": "^11.10.5",
> >     "@emotion/styled": "^11.10.5",
> >     "@headlessui/react": "^1.6.4",
> >     "@heroicons/react": "^1.0.6",
> >     "axios": "^0.27.2",
> >     "bootstrap": "^5.2.0",
> >     "eslint": "^8.29.0",
> >     "eslint-config-next": "^13.1.1",
> >     "fast-kde": "^0.2.1",
> >     "framer-motion": "^8.0.2",
> >     "next": "^13.1.1",
> >     "react": "^18.2.0",
> >     "react-dom": "^18.2.0",
> >     "valtio": "^1.6.1"
> >   },
> >   "devDependencies": {
> >     "@types/node": "17.0.4",
> >     "@types/react": "17.0.38",
> >     "@typescript-eslint/eslint-plugin": "^5.45.0",
> >     "autoprefixer": "^10.4.0",
> >     "eslint-config-standard-with-typescript": "^23.0.0",
> >     "eslint-plugin-import": "^2.25.2",
> >     "eslint-plugin-n": "^15.0.0",
> >     "eslint-plugin-promise": "^6.0.0",
> >     "eslint-plugin-react": "^7.31.11",
> >     "postcss": "^8.4.5",
> >     "prettier": "^2.5.1",
> >     "typescript": "*"
> >   }
> > }
> > ```
> 
> change your react/icons to "2.0.13" you have to use exact versions for chakra dependencies so remove the caret in front of each version. For example you have "@chakra-ui/icons": "^2.0.15" when it should be "@chakra-ui/icons": "2.0.13". Also make sure you delete current node_modules and package.json-lock and re-install all of your dependencies with npm i. I hope this helps!!

Thank you so much! It worked for me now. For people who have the same issues, please pin `@chakra-ui/react: 2.4.4` and `@chakra-ui/icons: 2.0.13` for now.

**Comment by MincePie** [comment]
I also have this issue. I tried pinning to each of 2.4.2 and 2.4.4. The specific issue identified is the same as in the original post. Node modules has an import as shown below - otherwise I don't import or export anything called chakra.

```
 // src/icon.tsx
import {
  chakra,
  forwardRef,
  useStyleConfig
} from "@chakra-ui/system";
```

**Comment by jun0222** [comment]
> Thank you so much! It worked for me now. For people who have the same issues, please pin @chakra-ui/react: 2.4.4 and @chakra-ui/icons: 2.0.13 for now.

This way I was able to work around the problem.
Thank you!

Also, "@chakra-ui/accordion" had the same problem, so
Fixed to "2.0.4". Then it was resolved.
```
"@chakra-ui/accordion": "2.0.4"
```

**Comment by bigwoof91** [comment]
https://github.com/chakra-ui/chakra-ui/issues/7170#issuecomment-1365886860
👆 This happened for me when bumping `@chakra-ui/react` from `v2.4.4` to `v2.4.5`

**Comment by DarrenBaldwin07** [comment]
@segunadebayo This issue is identical :https://github.com/chakra-ui/chakra-ui/issues/6942

**Comment by segunadebayo** [comment]
This issue happened due to our recent move to `.mjs` file extensions for better ESM detection. Some of our internal dependencies did not fully support ESM.

I've gone ahead to fix most of the ESM/CJS-related errors. We'll publish an update shortly.

If, after upgrading and the problem still exists in your application, please open a new issue, and we'll look into it.

**Comment by MincePie** [comment]
Why is this closed? I can't find a version that works.

**Comment by MincePie** [comment]
> > Thank you so much! It worked for me now. For people who have the same issues, please pin @chakra-ui/react: 2.4.4 and @chakra-ui/icons: 2.0.13 for now.
> 
> This way I was able to work around the problem. Thank you!
> 
> Also, "@chakra-ui/accordion" had the same problem, so Fixed to "2.0.4". Then it was resolved.
> 
> ```
> "@chakra-ui/accordion": "2.0.4"
> ```

Chakra icons does not have a version available with this number. I tried 2.0.1 to try and use your solution but am getting the same issue

**Comment by brandonLyonMM** [comment]
This is still happening with a fresh install of the latest version of Chakra UI, in particular with a fresh install of the latest version of Next.js.

**Comment by GorgeousPuree** [comment]
> This is still happening with a fresh install of the latest version of Chakra UI, in particular with a fresh install of the latest version of Next.js.

Same

**Comment by gu1ma** [comment]
I am having the same problem 

> > This is still happening with a fresh install of the latest version of Chakra UI, in particular with a fresh install of the latest version of Next.js.
> 
> Same

**Comment by Rzycka** [comment]
@AE-0h thanks a lot for your solution! I had the same problem and changing the versions worked!

**Comment by Rzycka** [comment]
> > Same issues here. Both 2.4.2 and 2.4.4 do not work for me. My package.json is:
> > ```
> >   "private": true,
> >   "scripts": {
> >     "dev": "next dev",
> >     "build": "next build",
> >     "start": "next start"
> >   },
> >   "dependencies": {
> >     "@chakra-ui/icons": "^2.0.15",
> >     "@chakra-ui/react": "2.4.2",
> >     "@emotion/react": "^11.10.5",
> >     "@emotion/styled": "^11.10.5",
> >     "@headlessui/react": "^1.6.4",
> >     "@heroicons/react": "^1.0.6",
> >     "axios": "^0.27.2",
> >     "bootstrap": "^5.2.0",
> >     "eslint": "^8.29.0",
> >     "eslint-config-next": "^13.1.1",
> >     "fast-kde": "^0.2.1",
> >     "framer-motion": "^8.0.2",
> >     "next": "^13.1.1",
> >     "react": "^18.2.0",
> >     "react-dom": "^18.2.0",
> >     "valtio": "^1.6.1"
> >   },
> >   "devDependencies": {
> >     "@types/node": "17.0.4",
> >     "@types/react": "17.0.38",
> >     "@typescript-eslint/eslint-plugin": "^5.45.0",
> >     "autoprefixer": "^10.4.0",
> >     "eslint-config-standard-with-typescript": "^23.0.0",
> >     "eslint-plugin-import": "^2.25.2",
> >     "eslint-plugin-n": "^15.0.0",
> >     "eslint-plugin-promise": "^6.0.0",
> >     "eslint-plugin-react": "^7.31.11",
> >     "postcss": "^8.4.5",
> >     "prettier": "^2.5.1",
> >     "typescript": "*"
> >   }
> > }
> > ```
> 
> change your react/icons to "2.0.13" you have to use exact versions for chakra dependencies so remove the caret in front of each version. For example you have "@chakra-ui/icons": "^2.0.15" when it should be "@chakra-ui/icons": "2.0.13". Also make sure you delete current node_modules and package.json-lock and re-install all of your dependencies with npm i. I hope this helps!!

@AE-0h thanks a lot for your solution! I had the same problem and changing the versions worked!
